# Generated by Django 3.1 on 2020-12-14 12:04

import django.core.validators
from django.db import migrations, models
import django_unixdatetimefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUpload',
            fields=[
                ('tsync_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=14)),
                ('full_address', models.TextField(blank=True, max_length=512)),
                ('name_of_university', models.CharField(max_length=256)),
                ('graduation_year', models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2020)])),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(4.0)])),
                ('experience_in_months', models.IntegerField(blank=True, default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_work_place_name', models.CharField(blank=True, max_length=256)),
                ('applying_in', models.CharField(choices=[('MOBILE', 'Mobile'), ('BACKEND', 'Backend')], default='Backend', max_length=14)),
                ('expected_salary', models.IntegerField(default=30000, validators=[django.core.validators.MinValueValidator(15000), django.core.validators.MaxValueValidator(60000)])),
                ('field_buzz_reference', models.CharField(blank=True, max_length=256)),
                ('github_project_url', models.URLField(max_length=512)),
                ('cv_file_tsync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('on_spot_update_time', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True)),
                ('on_spot_creation_time', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
