# Generated by Django 3.1 on 2020-12-14 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoupload',
            name='cgpa',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
