# Generated by Django 3.1 on 2020-12-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201214_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
