# Generated by Django 3.1 on 2020-12-17 13:41

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvfileupload',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[api.validators.validate_file_size]),
        ),
    ]
