# Generated by Django 3.1 on 2020-12-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cvfileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvfileupload',
            old_name='cv_document',
            new_name='document',
        ),
    ]
